### ISSUE TITLE
Remove Favorite from api is not working as expected.

### ISSUE THREAD

**Issue by ogranadagl** [ogranadagl/gorilla-cast#16]
## Description
Given:
 ```javascript
const data = await api.search('software');
// where 
console.log(data[0]);
/*
{wrapperType: "track", kind: "song", artistId: 4369635, collectionId: 342932999,
  trackId: 342933005, …}
*/
 ```

The following code:
 ```javascript
api.addFavorite(data[0])
 ```
Adds the element `data[0]` into favorites list.

However, when you use:
 ```javascript
api.removeFavorite(data[0]):
 ```
The element is not removed from favorites

## Expected behavior
The element would be removed from favorites list.

## Evidence image
![image](https://user-images.githubusercontent.com/61161118/75175802-02b19e00-5701-11ea-8c63-4dcb09f36758.png)

**Comment by alejandrobenjumeaGL** [comment]
Just checked the API behaviour, and it is working as expected. Please use favorite ID instead trackId.
If you need that method, please feel free to do it,  you can modify it as you like
